#
#
#                THIS IS THE LITE VERSION OF THE PLUGIN.
#                   PURCHASE THE FULL PLUGIN TO BE
#                   ABLE TO CHANGE FEATURES SUCH AS
#                       THE BLACKLISTED WORDS.
#
#